using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WordsList : MonoBehaviour
{
    public WordsClass[] eazy = {
        new WordsClass("català",    "cata<b><u>la</b></u>",     "català",     "catala",     "catalá"),
        new WordsClass("pera",      "<b><u>pe</b></u>ra",       "pèra",       "pera",       "péra"),
        new WordsClass("galàxia",   "ga<b><u>la</b></u>xia",    "galàxia",    "galaxia",    "galáxia"),
        new WordsClass("ànima",     "<b><u>a</b></u>nima",      "ànima",      "anima",      "ánima"),
        new WordsClass("camió",     "ca<b><u>mio</b></u>",      "camiò",      "camio",      "camió"),
        new WordsClass("aquí",      "a<b><u>qui</b></u>",       "aquì",       "aqui",       "aquí"),
        new WordsClass("sabó",      "sa<b><u>bo</b></u>",       "sabò",       "sabo",       "sabó"),
        new WordsClass("aigua",     "<b><u>ai</u></b>gua",      "aìgua",      "aigua",      "aígua"),
        new WordsClass("érem",      "<b><u>e</u></b>rem",       "èrem",       "erem",       "érem"),
        new WordsClass("telèfon",   "te<b><u>le</u></b>fon",    "telèfon",    "telefon",    "teléfon"),
        new WordsClass("calendari", "calen<b><u>da</u></b>ri",  "calendàri",  "calendari",  "calendári"),
        new WordsClass("excursió",  "excur<b><u>sio</u></b>",   "excursiò",   "excursio",   "excurció"),
        new WordsClass("màquina",   "<b><u>ma</u></b>quina",    "màquina",    "maquina",    "máquina"),
        new WordsClass("cara",      "<b><u>ca</u></b>ra",       "càra",       "cara",       "cára"),
        new WordsClass("bolígraf",  "bo<b><u>li</u></b>graf",   "bolìgraf",   "boligraf",   "bolígraf"),
        new WordsClass("cullera",   "cu<b><u>lle</u></b>ra",    "cullèra",    "cullera",    "culléra"),
        new WordsClass("dèbil",     "<b><u>de</u></b>bil",      "dèbil",      "debil",      "débil"),
        new WordsClass("estómac",   "es<b><u>to</u></b>mac",    "estòmac",    "estomac",    "estómac"),
        new WordsClass("fotògraf",  "fo<b><u>to</u></b>graf",   "fotògraf",   "fotograf",   "fotógraf"),
        new WordsClass("gairebé",   "gaire<b><u>be</u></b>",    "gairebè",    "gairabe",    "gairebé"),
        new WordsClass("rodo",      "<b><u>ro</u></b>do",       "ròdo",       "rodo",       "ródo"),
        new WordsClass("palau",     "<b><u>pa</u></b>lau",      "pàlau",      "palau",      "pálau"),
        new WordsClass("pòster",    "<b><u>pòs</u></b>ter",     "pòster",     "poster",     "póster"),
        new WordsClass("cadira",    "ca<b><u>di</u></b>ra",     "cadìra",     "cadira",     "cadíra"),
        new WordsClass("córrer",    "<b><u>cor</u></b>rer",     "còrrer",     "correr",     "córrer"),
        new WordsClass("ratolí",    "rato<b><u>li</u></b>",     "ratolì",     "ratoli",     "ratolí"),
        new WordsClass("llapis",    "<b><u>lla</u></b>pis",     "llàpis",     "llapis",     "llápis"),
        new WordsClass("congrés",   "con<b><u>gres</u></b>",    "congrès",    "congres",    "congrés"),
        new WordsClass("lògic",     "<b><u>lo</u></b>gic",      "lògic",      "logic",      "lógic"),
        new WordsClass("àngel",     "<b><u>an</u></b>gel",      "àngel",      "angel",      "ángel"),
        new WordsClass("cafè",      "ca<b><u>fe</u></b>",       "cafè",       "cafe",       "café"),
        new WordsClass("núvol",     "<b><u>nu</u></b>vol",      "nùvol",      "nuvol",      "núvol"),
        new WordsClass("nerviós",   "nervi<b><u>os</u></b>",    "nerviòs",    "nervios",    "nerviós"),
        new WordsClass("segon",     "se<b><u>gon</u></b>",      "segòn",      "segon",      "segón"),
        new WordsClass("caminaran", "camina<b><u>ran</u></b>",  "caminaràn",  "caminaran",  "caminarán"),
        new WordsClass("ningú",     "nin<b><u>gu</u></b>",      "ningù",      "ningu",      "ningú"),
        new WordsClass("passadís",  "passa<b><u>dis</u></b>",   "passadìs",   "passadis",   "passadís"),
        new WordsClass("pingüí",    "pin<b><u>güi</u></b>",     "pinguì",     "pingüi",     "pingüí"),
        new WordsClass("urbà",      "ur<b><u>bà</u></b>",       "urbà",       "urba",       "urbá"),
        new WordsClass("ratolí",    "rato<b><u>li</u></b>",     "ratolì",     "ratoli",     "ratolí"),
        new WordsClass("monòton",   "mo<b><u>no</u></b>ton",    "monòton",    "monoton",    "monóton"),
        new WordsClass("algun",     "al<b><u>gun</u></b>",      "algùn",      "algun",      "algún"),
        new WordsClass("príncep",   "<b><u>prin</u></b>cep",    "prìncep",    "princep",    "príncep"),
        new WordsClass("correspon", "cor<b><u>res</u></b>pon",  "corrèspon",  "correspon",  "corréspon"),
        new WordsClass("plàtan",    "<b><u>pla</u></b>tan",     "plàtan",     "platan",     "plátan"),
        new WordsClass("germà",     "ger<b><u>ma</u></b>",      "germà",      "germa",      "germá"),
        new WordsClass("Itàlia",    "I<b><u>tà</u></b>lia",     "Itàlia",     "Italia",     "Itália"),
        new WordsClass("permís",    "per<b><u>mis</u></b>",     "permìs",     "permis",     "permís"),
        new WordsClass("país",      "<b><u>pais</u></b>",       "paìs",       "pais",       "país"),
        new WordsClass("plàstic",   "<b><u>plas</u></b>tic",    "plàstic",    "plastic",    "plástic"),
        new WordsClass("padrí",     "pa<b><u>dri</u></b>",      "padrì",      "padri",      "padrí"),
        new WordsClass("submarí",   "subma<b><u>ri</u></b>",    "submarì",    "submari",    "submarí"),
        new WordsClass("veí",       "<b><u>vei</u></b>",        "veì",        "vei",        "veí"),
        new WordsClass("acabaran",  "aca<b><u>ba</u></b>ran",   "acabàran",   "acabaran",   "acabáran"),
        new WordsClass("remei",     "<b><u>re</u></b>mei",      "rèmei",      "remei",      "rémei"),
        new WordsClass("síndria",   "<b><u>sin</u></b>dria",    "sìndria",    "sindria",    "síndria"),
        new WordsClass("tornavís",  "torna<b><u>vis</u></b>",   "tornavìs",   "tornavis",   "tornavís"),
        new WordsClass("semàfor",   "se<b><u>ma</u></b>for",    "semàfor",    "semafor",    "semáfor"),
        new WordsClass("camí",      "ca<b><u>mi</u></b>",       "camì",       "cami",       "camí"),
        new WordsClass("llatí",     "lla<b><u>ti</u></b>",      "llatì",      "llati",      "llatí"),
        new WordsClass("oceà",      "oce<b><u>a</u></b>",       "oceà",       "ocea",       "oceá"),
        new WordsClass("cabàs",     "ca<b><u>bas</u></b>",      "cabàs",      "cabas",      "cabás"),
        new WordsClass("meravellós","merave<b><u>llos</u></b>", "meravellòs", "meravellos", "meravellós"),
        new WordsClass("restes",    "<b><u>res</u></b>tes",     "rèstes",     "restes",     "réstes"),
        new WordsClass("meló",      "me<b><u>lo</u></b>",       "melò",       "melo",       "meló"),
        new WordsClass("carbó",     "car<b><u>bo</u></b>",      "carbò",      "carbo",      "carbó"),
        new WordsClass("camió",     "cami<b><u>o</u></b>",      "camiò",      "camio",      "camió"),
        new WordsClass("esglaó",    "esgla<b><u>o</u></b>",     "esglaò",     "esglao",     "esglaó"),
        new WordsClass("embaràs",   "emba<b><u>ras</u></b>",    "embaràs",    "embaras",    "embarás"),
        new WordsClass("capatàs",   "capa<b><u>tas</u></b>",    "capatàs",    "capatas",    "capatás"),
        new WordsClass("jardí",     "jar<b><u>di</u></b>",      "jardì",      "jardi",      "jardí"),
        new WordsClass("població",  "pobla<b><u>ció</u></b>",   "poblaciò",   "poblacio",   "població"),
        new WordsClass("sistema",   "sis<b><u>te</u></b>ma",    "sistèma",    "sistema",    "sistéma"),
        new WordsClass("poble",     "<b><u>po</u></b>ble",      "pòble",      "poble",      "póble"),
        new WordsClass("foren",     "<b><u>fo</u></b>ren",      "fòren",      "foren",      "fóren"),
        new WordsClass("època",     "<b><u>e</u></b>poca",      "època",      "epoca",      "época"),
        new WordsClass("haver",     "ha<b><u>ver</u></b>",      "havèr",      "haver",      "havér"),
        new WordsClass("cada",      "<b><u>ca</u></b>da",       "cáda",       "cada",       "cáda"),
        new WordsClass("eleccions", "elecci<b><u>ons</u></b>",  "elecciòns",  "eleccions",  "eleccións"),
        new WordsClass("diverses",  "di<b><u>ver</u></b>ses",   "divèrses",   "diverses",   "divérses"),
        new WordsClass("obra",      "<b><u>o</u></b>bra",       "òbra",       "obra",       "óbra"),
        new WordsClass("partir",    "par<b><u>tir</u></b>",     "partìr",     "partir",     "partír"),
        new WordsClass("tipus",     "<b><u>ti</u></b>pus",      "tìpus",      "tipus",      "típus"),
        new WordsClass("vida",      "<b><u>vi</u></b>da",       "vìda",       "vida",       "vída"),
        new WordsClass("quatre",    "<b><u>qua</u></b>tre",     "quàtre",     "quatre",     "quátre"),
        new WordsClass("poc",       "<b><u>poc</u></b>",        "pòc",        "poc",        "póc"),
        new WordsClass("regió",     "re<b><u>gió</u></b>",      "regiò",      "regio",      "regió"),
        new WordsClass("exemple",   "ex<b><u>em</u></b>ple",    "exèmple",    "exemple",    "exémple"),
        new WordsClass("batalla",   "ba<b><u>ta</u></b>lla",    "batàlla",    "batalla",    "batálla"),
        new WordsClass("altre",     "<b><u>al</u></b>tre",      "àltre",      "altre",      "áltre"),
        new WordsClass("Joan",      "<b><u>Jo</u></b>an",       "Jòan",       "Joan",       "Jóan"),
        new WordsClass("actualment","actual<b><u>ment</u></b>", "actualmènt", "actualment", "actualmént"),
        new WordsClass("tenen",     "<b><u>te</u></b>nen",      "tènen",      "tenen",      "ténen"),
        new WordsClass("dins",      "<b><u>dins</u></b>",       "dìns",       "dins",       "díns"),
        new WordsClass("llavors",   "lla<b><u>vors</u></b>",    "llavòrs",    "llavors",    "llavórs"),
        new WordsClass("centre",    "cen<b><u>tre</u></b>",     "cèntre",     "centre",     "céntre"),
        new WordsClass("algunes",   "al<b><u>gu</u></b>nes",    "algùnes",    "algunes",    "algúnes"),
        new WordsClass("important", "impor<b><u>tant</u></b>",  "importànt",  "important",  "importánt"),
        new WordsClass("altra",     "<b><u>al</u></b>tra",      "àltra",      "altra",      "áltra"),
        new WordsClass("terra",     "<b><u>ter</u></b>ra",      "tèrra",      "terra",      "térra"),
        new WordsClass("antic",     "an<b><u>tic</u></b>",      "antìr",      "antic",      "antíc"),
        new WordsClass("tenia",     "te<b><u>ni</u></b>a",      "tenìa",      "tenia",      "tenía"),
        new WordsClass("zona",      "<b><u>zo</u></b>na",       "zòna",       "zona",       "zóna"),
        new WordsClass("obres",     "<b><u>o</u></b>bres",      "òbres",      "obres",      "óbres"),
        new WordsClass("estava",    "es<b><u>ta</u></b>va",     "estàva",     "estava",     "estáva"),
        new WordsClass("pare",      "<b><u>pa</u></b>re",       "pàre",       "pare",       "páre"),
        new WordsClass("ara",       "<b><u>a</u></b>ra",        "àra",        "ara",        "ára"),
        new WordsClass("havien",    "havi<b><u>en</u></b>",     "havièn",     "havien",     "havién"),
        new WordsClass("començar",  "co<b><u>men</u></b>çar",   "comènçar",   "començar",   "coménçar"),
        new WordsClass("història",  "his<b><u>to</u></b>ria",   "història",   "historia",   "história"),
        new WordsClass("morir",     "mo<b><u>rir</u></b>",      "mòrir",      "morir",      "mórir"),
        new WordsClass("nacional",  "nacio<b><u>nal</u></b>",   "nacionàl",   "nasional",   "nacionál"),
        new WordsClass("final",     "<b><u>fi</u></b>nal",      "fìnal",      "final",      "fínal"),
        new WordsClass("música",    "<b><u>mú</u></b>sica",     "mùsica",     "musica",     "música"),
        new WordsClass("majoria",   "majo<b><u>ri</u></b>a",    "majorìa",    "majoria",    "majoría"),


    };



    public WordsClass[] medium = {
        new WordsClass("créixer", "creixer", "crèixer", "creixer", "créixer"),
    };

    public WordsClass[] hard = {
        new WordsClass("renou",     "<b><u>re</u></b>nou", "rènou", "renou", "rénou"),
    };

    public void Awake()
    {
        eazy[0] = new WordsClass("Català", "Catala", "Català", "Catala", "Catalá");
    }
}


