using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WordsList : MonoBehaviour
{
    public WordsClass[] eazy = {
        new WordsClass("català",    "cata<b><u>la</b></u>",     "català",     "catala",     "catalá"),
        new WordsClass("pera",      "<b><u>pe</b></u>ra",       "pèra",       "pera",       "péra"),
        //new WordsClass("galàxia",   "ga<b><u>la</b></u>xia",    "galàxia",    "galaxia",    "galáxia"),
        new WordsClass("ànima",     "<b><u>a</b></u>nima",      "ànima",      "anima",      "ánima"),
        new WordsClass("camió",     "ca<b><u>mio</b></u>",      "camiò",      "camio",      "camió"),
        new WordsClass("aquí",      "a<b><u>qui</b></u>",       "aquì",       "aqui",       "aquí"),
        new WordsClass("sabó",      "sa<b><u>bo</b></u>",       "sabò",       "sabo",       "sabó"),
        new WordsClass("aigua",     "<b><u>ai</u></b>gua",      "aìgua",      "aigua",      "aígua"),
        new WordsClass("telèfon",   "te<b><u>le</u></b>fon",    "telèfon",    "telefon",    "teléfon"),
        new WordsClass("calendari", "calen<b><u>da</u></b>ri",  "calendàri",  "calendari",  "calendári"),
        new WordsClass("excursió",  "excursi<b><u>o</u></b>",   "excursiò",   "excursio",   "excursió"),
        new WordsClass("màquina",   "<b><u>ma</u></b>quina",    "màquina",    "maquina",    "máquina"),
        new WordsClass("cara",      "<b><u>ca</u></b>ra",       "càra",       "cara",       "cára"),
        new WordsClass("bolígraf",  "bo<b><u>li</u></b>graf",   "bolìgraf",   "boligraf",   "bolígraf"),
        new WordsClass("cullera",   "cu<b><u>lle</u></b>ra",    "cullèra",    "cullera",    "culléra"),
        new WordsClass("dèbil",     "<b><u>de</u></b>bil",      "dèbil",      "debil",      "débil"),
        new WordsClass("estómac",   "es<b><u>to</u></b>mac",    "estòmac",    "estomac",    "estómac"),
        new WordsClass("fotògraf",  "fo<b><u>to</u></b>graf",   "fotògraf",   "fotograf",   "fotógraf"),
        new WordsClass("rodó",      "ro<b><u>do</u></b>",       "rodò",       "rodo",       "rodó"),
        new WordsClass("palau",     "<b><u>pa</u></b>lau",      "pàlau",      "palau",      "pálau"),
        new WordsClass("cadira",    "ca<b><u>di</u></b>ra",     "cadìra",     "cadira",     "cadíra"),
        new WordsClass("córrer",    "<b><u>cor</u></b>rer",     "còrrer",     "correr",     "córrer"),
        new WordsClass("ratolí",    "rato<b><u>li</u></b>",     "ratolì",     "ratoli",     "ratolí"),
        new WordsClass("llapis",    "<b><u>lla</u></b>pis",     "llàpis",     "llapis",     "llápis"),
        new WordsClass("congrés",   "con<b><u>gres</u></b>",    "congrès",    "congres",    "congrés"),
        new WordsClass("lògic",     "<b><u>lo</u></b>gic",      "lògic",      "logic",      "lógic"),
        new WordsClass("àngel",     "<b><u>an</u></b>gel",      "àngel",      "angel",      "ángel"),
        new WordsClass("cafè",      "ca<b><u>fe</u></b>",       "cafè",       "cafe",       "café"),
        new WordsClass("núvol",     "<b><u>nu</u></b>vol",      "nùvol",      "nuvol",      "núvol"),
        new WordsClass("nerviós",   "nervi<b><u>os</u></b>",    "nerviòs",    "nervios",    "nerviós"),
        new WordsClass("segon",     "se<b><u>gon</u></b>",      "segòn",      "segon",      "segón"),
        new WordsClass("ningú",     "nin<b><u>gu</u></b>",      "ningù",      "ningu",      "ningú"),
        new WordsClass("passadís",  "passa<b><u>dis</u></b>",   "passadìs",   "passadis",   "passadís"),
        new WordsClass("paper",     "pa<b><u>per</u></b>",      "papèr",      "paper",      "papér"),
        new WordsClass("urbà",      "ur<b><u>bà</u></b>",       "urbà",       "urba",       "urbá"),
        new WordsClass("ratolí",    "rato<b><u>li</u></b>",     "ratolì",     "ratoli",     "ratolí"),
        new WordsClass("algun",     "al<b><u>gun</u></b>",      "algùn",      "algun",      "algún"),
        new WordsClass("príncep",   "<b><u>prin</u></b>cep",    "prìncep",    "princep",    "príncep"),
        new WordsClass("plàtan",    "<b><u>pla</u></b>tan",     "plàtan",     "platan",     "plátan"),
        new WordsClass("germà",     "ger<b><u>ma</u></b>",      "germà",      "germa",      "germá"),
        new WordsClass("cançó",    "can<b><u>ço</u></b>",       "cançò",      "canço",      "cançó"),
        new WordsClass("permís",    "per<b><u>mis</u></b>",     "permìs",     "permis",     "permís"),
        new WordsClass("país",      "pa<b><u>is</u></b>",       "paìs",       "pais",       "país"),
        new WordsClass("plàstic",   "<b><u>plas</u></b>tic",    "plàstic",    "plastic",    "plástic"),
        new WordsClass("padrí",     "pa<b><u>dri</u></b>",      "padrì",      "padri",      "padrí"),
        new WordsClass("submarí",   "subma<b><u>ri</u></b>",    "submarì",    "submari",    "submarí"),
        new WordsClass("veí",       "ve<b><u>i</u></b>",        "veì",        "vei",        "veí"),
        new WordsClass("poma",      "<b><u>po</u></b>ma",       "pòma",       "poma",       "póma"),
        new WordsClass("síndria",   "<b><u>sin</u></b>dria",    "sìndria",    "sindria",    "síndria"),
        new WordsClass("tornavís",  "torna<b><u>vis</u></b>",   "tornavìs",   "tornavis",   "tornavís"),
        new WordsClass("semàfor",   "se<b><u>ma</u></b>for",    "semàfor",    "semafor",    "semáfor"),
        new WordsClass("camí",      "ca<b><u>mi</u></b>",       "camì",       "cami",       "camí"),
        new WordsClass("llatí",     "lla<b><u>ti</u></b>",      "llatì",      "llati",      "llatí"),
        new WordsClass("oceà",      "oce<b><u>a</u></b>",       "oceà",       "ocea",       "oceá"),
        new WordsClass("restes",    "<b><u>res</u></b>tes",     "rèstes",     "restes",     "réstes"),
        new WordsClass("meló",      "me<b><u>lo</u></b>",       "melò",       "melo",       "meló"),
        new WordsClass("carbó",     "car<b><u>bo</u></b>",      "carbò",      "carbo",      "carbó"),
        new WordsClass("esglaó",    "esgla<b><u>o</u></b>",     "esglaò",     "esglao",     "esglaó"),
        new WordsClass("embaràs",   "emba<b><u>ras</u></b>",    "embaràs",    "embaras",    "embarás"),
        new WordsClass("capatàs",   "capa<b><u>tas</u></b>",    "capatàs",    "capatas",    "capatás"),
        new WordsClass("jardí",     "jar<b><u>di</u></b>",      "jardì",      "jardi",      "jardí"),
        new WordsClass("població",  "poblaci<b><u>ó</u></b>",   "poblaciò",   "poblacio",   "població"),
        new WordsClass("sistema",   "sis<b><u>te</u></b>ma",    "sistèma",    "sistema",    "sistéma"),
        new WordsClass("poble",     "<b><u>po</u></b>ble",      "pòble",      "poble",      "póble"),
        new WordsClass("època",     "<b><u>e</u></b>poca",      "època",      "epoca",      "época"),
        new WordsClass("haver",     "ha<b><u>ver</u></b>",      "havèr",      "haver",      "havér"),
        new WordsClass("cada",      "<b><u>ca</u></b>da",       "càda",       "cada",       "cáda"),
        new WordsClass("obra",      "<b><u>o</u></b>bra",       "òbra",       "obra",       "óbra"),
        new WordsClass("partir",    "par<b><u>tir</u></b>",     "partìr",     "partir",     "partír"),
        new WordsClass("tipus",     "<b><u>ti</u></b>pus",      "tìpus",      "tipus",      "típus"),
        new WordsClass("vida",      "<b><u>vi</u></b>da",       "vìda",       "vida",       "vída"),
        new WordsClass("quatre",    "<b><u>qua</u></b>tre",     "quàtre",     "quatre",     "quátre"),
        new WordsClass("poc",       "<b><u>poc</u></b>",        "pòc",        "poc",        "póc"),
        new WordsClass("regió",     "regi<b><u>ó</u></b>",      "regiò",      "regio",      "regió"),
        new WordsClass("exemple",   "ex<b><u>em</u></b>ple",    "exèmple",    "exemple",    "exémple"),
        new WordsClass("batalla",   "ba<b><u>ta</u></b>lla",    "batàlla",    "batalla",    "batálla"),
        new WordsClass("altre",     "<b><u>al</u></b>tre",      "àltre",      "altre",      "áltre"),
        new WordsClass("Joan",      "Jo<b><u>an</u></b>",       "Joàn",       "Joan",       "Joán"),
        new WordsClass("tenen",     "<b><u>te</u></b>nen",      "tènen",      "tenen",      "ténen"),
        new WordsClass("dins",      "<b><u>dins</u></b>",       "dìns",       "dins",       "díns"),
        new WordsClass("llavors",   "lla<b><u>vors</u></b>",    "llavòrs",    "llavors",    "llavórs"),
        new WordsClass("centre",    "cen<b><u>tre</u></b>",     "cèntre",     "centre",     "céntre"),
        new WordsClass("algunes",   "al<b><u>gu</u></b>nes",    "algùnes",    "algunes",    "algúnes"),
        new WordsClass("important", "impor<b><u>tant</u></b>",  "importànt",  "important",  "importánt"),
        new WordsClass("altra",     "<b><u>al</u></b>tra",      "àltra",      "altra",      "áltra"),
        new WordsClass("terra",     "<b><u>ter</u></b>ra",      "tèrra",      "terra",      "térra"),
        new WordsClass("antic",     "an<b><u>tic</u></b>",      "antìc",      "antic",      "antíc"),
        //new WordsClass("tenia",     "te<b><u>ni</u></b>a",      "tenìa",      "tenia",      "tenía"),
        new WordsClass("zona",      "<b><u>zo</u></b>na",       "zòna",       "zona",       "zóna"),
        new WordsClass("obres",     "<b><u>o</u></b>bres",      "òbres",      "obres",      "óbres"),
        new WordsClass("estava",    "es<b><u>ta</u></b>va",     "estàva",     "estava",     "estáva"),
        new WordsClass("pare",      "<b><u>pa</u></b>re",       "pàre",       "pare",       "páre"),
        new WordsClass("ara",       "<b><u>a</u></b>ra",        "àra",        "ara",        "ára"),
        new WordsClass("havien",    "ha<b><u>vi</u></b>en",     "havìen",     "havien",     "havíen"),
        new WordsClass("començar",  "co<b><u>men</u></b>çar",   "comènçar",   "començar",   "coménçar"),
        //new WordsClass("història",  "his<b><u>to</u></b>ria",   "història",   "historia",   "história"),
        new WordsClass("morir",     "mo<b><u>rir</u></b>",      "mòrir",      "morir",      "mórir"),
        new WordsClass("nacional",  "nacio<b><u>nal</u></b>",   "nacionàl",   "nasional",   "nacionál"),
        new WordsClass("final",     "<b><u>fi</u></b>nal",      "fìnal",      "final",      "fínal"),
        new WordsClass("cantó",     "can<b><u>to</u></b>",      "cantò",      "canto",      "cantó"),
        new WordsClass("balcó",     "bal<b><u>co</u></b>",      "balcò",      "balco",      "balcó"),
        new WordsClass("tambor",    "tam<b><u>bor</u></b>",     "tambòr",     "tambor",     "tambór"),
        new WordsClass("pantaló",   "panta<b><u>lo</u></b>",    "pantalò",    "pantalo",    "pantaló"),
        new WordsClass("armari",    "ar<b><u>ma</u></b>ri",     "armàri",     "armari",     "armári"),
        new WordsClass("avió",      "avi<b><u>o</u></b>",       "aviò",       "avio",       "avió"),
        new WordsClass("pastís",    "pas<b><u>tis</u></b>",     "pastìs",     "pastis",     "pastís"),
        new WordsClass("formatge",  "for<b><u>mat</u></b>ge",   "formàtge",   "formatge",   "formátge"),
        new WordsClass("finestra",  "fi<b><u>nes</u></b>tra",   "finèstra",   "finestra",   "finéstra"),
        new WordsClass("pirata",    "pi<b><u>ra</u></b>ta",     "piràta",     "pirata",     "piráta"),
        new WordsClass("castell",   "cas<b><u>tell</u></b>",    "castèll",    "castell",    "castéll"),
        new WordsClass("porta",     "<b><u>por</u></b>ta",      "pòrta",      "porta",      "pórta"),
        new WordsClass("nina",      "<b><u>ni</u></b>na",       "nìna",       "nina",       "nína"),
        new WordsClass("globus",    "<b><u>glo</u></b>bus",     "glòbus",     "globus",     "glóbus"),
        new WordsClass("sabata",    "sa<b><u>ba</u></b>ta",     "sabàta",     "sabata",     "sabáta"),
        new WordsClass("gelat",     "ge<b><u>lat</u></b>",      "gelàt",      "gelat",      "gelát"),
        new WordsClass("amic",      "a<b><u>mic</u></b>",       "amìc",       "amic",       "amíc"),
        new WordsClass("pintor",    "pin<b><u>tor</u></b>",     "pintòr",     "pintor",     "pintór"),
        new WordsClass("estrella",  "es<b><u>tre</u></b>lla",   "estrèlla",   "estrella",   "estrélla"),
        new WordsClass("sofà",      "so<b><u>fa</u></b>",       "sofà",       "sofa",       "sofá"),
        new WordsClass("dinosaure", "dino<b><u>sau</u></b>re",  "dinosàure",  "dinosaure",  "dinosáure"),
        new WordsClass("aventura",  "aven<b><u>tu</u></b>ra",   "aventùra",   "aventura",   "aventúra"),





    };



    public WordsClass[] medium = {
        new WordsClass("créixer",   "creixer",                  "crèixer",    "creixer",    "créixer"),
        new WordsClass("gairebé",   "gaire<b><u>be</u></b>",    "gairebè",    "gairabe",    "gairebé"),
        new WordsClass("caminaran", "camina<b><u>ran</u></b>",  "caminaràn",  "caminaran",  "caminarán"),
        new WordsClass("pòster",    "<b><u>pos</u></b>ter",     "pòster",     "poster",     "póster"),
        new WordsClass("acabaran",  "acaba<b><u>ran</u></b>",   "acabaràn",   "acabaran",   "acabarán"),
        new WordsClass("eleccions", "elecci<b><u>ons</u></b>",  "elecciòns",  "eleccions",  "eleccións"),
        new WordsClass("correspon", "corres<b><u>pon</u></b>",  "correspòn",  "correspon",  "correspón"),
        new WordsClass("rei",       "<b><u>rei</u></b>",        "rèi",        "rei",        "réi"),
        new WordsClass("pàgina",    "<b><u>pa</u></b>gina",     "pàgína",     "pagina",     "página"),
        new WordsClass("màgic",     "<b><u>ma</u></b>gic",      "màgic",      "magic",      "mágic"),
        new WordsClass("plàstic",   "<b><u>plas</u></b>tic",    "plàstic",    "plastic",    "plástic"),
        new WordsClass("càmera",    "<b><u>ca</u></b>mera",     "càmèra",     "camera",     "cámera"),
        new WordsClass("àngel",     "<b><u>an</u></b>gel",      "àngel",      "angel",      "ángel"),
        new WordsClass("còmic",     "<b><u>co</u></b>mic",      "còmic",      "comic",      "cómic"),
        new WordsClass("música",    "<b><u>mu</u></b>sica",     "mùsica",     "musica",     "música"),
        new WordsClass("taula",     "<b><u>tau</u></b>la",      "tàula",      "taula",      "táula"),
        new WordsClass("cantó",     "can<b><u>to</u></b>",      "cantò",      "canto",      "cantó"),
        new WordsClass("pluja",     "<b><u>plu</u></b>ja",      "plùja",      "pluja",      "plúja"),
        new WordsClass("números",   "<b><u>nu</u></b>meros",    "nùmeros",    "numeros",    "números"),
        new WordsClass("carnisser", "carni<b><u>sser</u></b>",  "carnissèr",  "carnisser",  "carnissér"),
        new WordsClass("paret",     "pa<b><u>ret</u></b>",      "parèt",      "paret",      "parét"),
        new WordsClass("gelat",     "ge<b><u>lat</u></b>",      "gelàt",      "gelat",      "gélat"),
        new WordsClass("botiga",    "bo<b><u>ti</u></b>ga",     "botìga",     "botiga",     "botíga"),
        new WordsClass("petó",      "pe<b><u>to</u></b>",       "petò",       "peto",       "petó"),
        new WordsClass("àrbre",     "<b><u>ar</u></b>bre",      "àrbre",      "arbre",      "árbre"),
        new WordsClass("avi",       "<b><u>a</u></b>vi",        "àvi",        "avi",        "ávi"),
        new WordsClass("cotxe",     "<b><u>cot</u></b>xe",      "còtxe",      "cotxe",      "cótxe"),
        new WordsClass("fàbrica",   "<b><u>fa</u></b>brica",    "fàbrica",    "fabrica",    "fábrica"),
        new WordsClass("pintura",   "pin<b><u>tu</u></b>ra",    "pintùra",    "pintura",    "pintúra"),
        new WordsClass("dibuix",    "di<b><u>buix</u></b>",     "dibùix",     "dibuix",     "dibúix"),
        new WordsClass("policia",   "poli<b><u>ci</u></b>a",    "policìa",    "policia",    "policía"),
        //new WordsClass("ràdio",     "<b><u>ra</u></b>dio",      "ràdio",      "radio",      "rádio"),
        new WordsClass("córrer",    "<b><u>cor</u></b>rer",     "còrrer",     "correr",     "córrer"),
        new WordsClass("muntanya",  "mun<b><u>ta</u></b>nya",   "muntànya",   "muntanya",   "muntánya"),
        new WordsClass("escola",    "es<b><u>co</u></b>la",     "escòla",     "escola",     "escóla"),
        new WordsClass("platja",    "<b><u>plat</u></b>ja",     "plàtja",     "platja",     "plátja"),
        new WordsClass("cartera",   "car<b><u>te</u></b>ra",    "cartèra",    "cartera",    "cartéra"),
        new WordsClass("meravellós","merave<b><u>llos</u></b>", "meravellòs", "meravellos", "meravellós"),
        new WordsClass("rellotge",  "re<b><u>llot</u></b>ge",   "rellòtge",   "rellotge",   "rellótge"),
        new WordsClass("diverses",  "di<b><u>ver</u></b>ses",   "divèrses",   "diverses",   "divérses"),
        new WordsClass("pilota",    "pi<b><u>lo</u></b>ta",     "pilòta",     "pilota",     "pilóta"),
        new WordsClass("joguina",   "jo<b><u>gui</u></b>na",    "joguìna",    "joguina",    "joguína"),
        new WordsClass("esquelet",  "esque<b><u>let</u></b>",   "esquelèt",   "esquelet",   "esquelét"),
        new WordsClass("bicicleta", "bici<b><u>cle</u></b>ta",  "biciclèta",  "bicicleta",  "bicicléta"),
        new WordsClass("ordinador", "ordina<b><u>dor</u></b>",  "ordinadòr",  "ordinador",  "ordinadór"),
        new WordsClass("ratolí",    "rato<b><u>li</u></b>",     "ratolì",     "ratoli",     "ratolí"),
        new WordsClass("xocolata",  "xoco<b><u>la</u></b>ta",   "xocolàta",   "xocolata",   "xocoláta"),
        new WordsClass("matemàtiques","mate<b><u>ma</u></b>tiques","matemàtiques", "matematiques","matemátiques"),
        new WordsClass("agrícola",  "a<b><u>gri</u></b>cola",      "agrìcola",     "agricola",    "agrícola"),
        new WordsClass("indígena",  "in<b><u>di</u></b>gena",      "indìgena",     "indigena",    "indígena"),
        new WordsClass("màniga",    "<b><u>ma</u></b>niga",        "màniga",       "maniga",      "mániga"),
        new WordsClass("anguila",   "an<b><u>gui</u></b>la",       "anguìla",      "anguila",     "anguíla"),
        new WordsClass("mètode",    "<b><u>me</u></b>tode",        "mètode",       "metode",      "métode"),
        new WordsClass("mecànica",  "me<b><u>cà</u></b>nica",      "mecànica",     "mecanica",    "mecánica"),
        new WordsClass("màxima",    "<b><u>ma</u></b>xima",        "màxima",       "maxima",      "máxima"),
        //new WordsClass("angúnia",   "an<b><u>gú</u></b>nia",       "angùnia",      "angunia",     "angúnia"),
        new WordsClass("sèrie",     "<b><u>se</u></b>rie",         "sèrie",        "serie",       "série"),
        new WordsClass("pèrdua",    "<b><u>per</u></b>dua",        "pèrdua",       "perdua",      "pérdua"),
        new WordsClass("aquàrium",  "a<b><u>quà</u></b>rium",      "aquàrium",     "aquarium",    "aquárium"),
        new WordsClass("àrea",      "<b><u>a</u></b>rea",          "àrea",         "area",        "área"),
        new WordsClass("mocador",   "moca<b><u>dor</u></b>",       "mocadòr",      "mocador",     "mocadór"),




    };

    public WordsClass[] hard = {
        new WordsClass("cabàs",     "ca<b><u>bas</u></b>",      "cabàs",      "cabas",      "cabás"),
        new WordsClass("érem",      "<b><u>e</u></b>rem",       "èrem",       "erem",       "érem"),
        new WordsClass("monòton",   "mo<b><u>no</u></b>ton",    "monòton",    "monoton",    "monóton"),
        new WordsClass("foren",     "<b><u>fo</u></b>ren",      "fòren",      "foren",      "fóren"),
        new WordsClass("túnel",     "<b><u>tu</u></b>nel",      "túnèl",      "tunel",      "túnel"),
        new WordsClass("brúixola",  "<b><u>brui</u></b>xola",   "brùixóla",   "bruixola",   "brúixola"),
        new WordsClass("àrbitre",   "<b><u>ar</u></b>bitre",    "àrbitre",    "arbitre",    "árbitre"),
        new WordsClass("sòlid",     "<b><u>so</u></b>lid",      "sòlid",      "solid",      "sólid"),
        new WordsClass("actualment","actual<b><u>ment</u></b>", "actualmènt", "actualment", "actualmént"),
        new WordsClass("televisor", "televi<b><u>sor</u></b>",  "televisòr",  "televisor",  "televisór"),
        new WordsClass("televisió", "televisi<b><u>o</u></b>",  "televisiò",  "televisio",  "televisió"),
        new WordsClass("adjectiu",  "adjec<b><u>tiu</u></b>",   "adjectìu",   "adjectiu",   "adjectíu"),
        new WordsClass("universitat",  "universi<b><u>tat</u></b>",  "universitàt",  "universitat",  "universitát"),
        new WordsClass("nòmada",       "<b><u>no</u></b>mada",       "nòmada",       "nomada",       "nómada"),
        new WordsClass("electricitat", "electrici<b><u>tat</u></b>", "electricitàt", "electricitat", "electricitát"),
        new WordsClass("extraordinari","extraordi<b><u>na</u></b>ri","extraordinàri","extraordinari","extraordinári"),
        new WordsClass("identitat",    "identi<b><u>tat</u></b>",    "identitàt",    "identitat",    "identítat"),
        new WordsClass("celebració",   "celebraci<b><u>o</u></b>",   "celebraciò",   "celebracio",   "celebració"),
        new WordsClass("secretària",   "secre<b><u>ta</u></b>ria",   "secretària",   "secretaria",   "secretária"),
        new WordsClass("secretaria",   "secreta<b><u>ri</u></b>a",   "secretarìa",   "secretaria",   "secretaría"),
        new WordsClass("pàncrees",     "<b><u>pan</u></b>crees",     "pàncrees",     "pancrees",     "páncrees"),
        new WordsClass("besàvia",      "be<b><u>sa</u></b>via",      "besàvia",      "besavia",      "besávia"),
        new WordsClass("colònia",      "co<b><u>lo</u></b>nia",      "colònia",      "colonia",      "colónia"),
        new WordsClass("harmònica",    "har<b><u>mò</u></b>nica",    "harmònica",    "harmonica",    "harmónica"),
        new WordsClass("llàgrima",     "<b><u>lla</u></b>grima",     "llàgrima",     "llagrima",     "llágrima"),
        new WordsClass("física",       "<b><u>fi</u></b>sica",       "fìsica",       "fisica",       "física"),
        new WordsClass("òptica",       "<b><u>op</u></b>tica",       "òptica",       "optica",       "óptica"),
        new WordsClass("família",      "fa<b><u>mi</u></b>lia",      "famìlia",      "familia",      "famíla"),
        new WordsClass("electrònica",  "elec<b><u>tro</u></b>nica",  "electrònica",  "electronica",  "electrónica"),
        new WordsClass("catifa",       "ca<b><u>ti</u></b>fa",       "catifa",       "catífa",       "catifa"),
        new WordsClass("guitarra",     "gui<b><u>ta</u></b>rra",     "guitarra",     "guitárrà",     "guitarra"),





    };

    public void Awake()
    {
        eazy[0] = new WordsClass("Català", "Catala", "Català", "Catala", "Catalá");
    }
}


